application: hungrynorse
version: 1
api_version: 1
runtime: python

handlers:
- url: .*
  script: main.py
  
- url: /css
  static_dir: css

- url: /(.*\.(gif|png|jpg))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg))